### ISSUE TITLE
Adjust Login Styling

### ISSUE THREAD

**Issue by markusguenther** [TYPO3-cookbooks/site-reviewtypo3org#11]
The login looks like there is not really a style and therefore I thought something is missing.
Tried to change that now.

PR is following!

**Comment by sgrossberndt** [comment]
Maybe this is also worth a bug report to the gerrit maintainers :-)

**Comment by markusguenther** [comment]
It depends on your auth method of Gerrit. The OpenID Login looks really different ;)
And I bet that they say it depends on the need of the project and so everybody can style it.
