### ISSUE TITLE
Add legal-notice link to review.typo3.org

### ISSUE THREAD

**Issue by stucki** [TYPO3-cookbooks/site-reviewtypo3org#30]
Please add a link "Legal Info" that points to https://typo3.org/legal-notice/ to the template.

**Comment by StephenKing** [comment]
@sgrossberndt sorry, just noticed that you self-assigned this to you. Started with that during yesterday's breakfast and finished it now.

Did you find a more clever solution? Do you think it's bad how I suggest it?

**Comment by sgrossberndt** [comment]
No thats fine. I started that during the sprint but did not get that far. Thanks!
